# R for travis: see documentation at https://jef.works/blog/2019/02/17/automate-testing-of-your-R-package/

language: R
cache: packages
warnings_are_errors: false

sudo: true
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

# for codecov
r_packages:
  - covr

# only report codecov after build is successful
after_success:
  - Rscript -e 'covr::codecov()'
